# Spécifiez l'image Docker à utiliser comme base pour les jobs
image: openjdk:latest

# Définition des étapes du pipeline
stages:
  - build
  - test
  - deploy

# Job de compilation
compile:
  stage: build
  script:
    - javac -d . src/*.java

# Job de test
test:
  stage: test
  script:
    - java -cp . YourTestClass

# Job de déploiement (exemple : déploiement sur un serveur après les tests réussis)
deploy:
  stage: deploy
  script:
    - echo "Déploiement du code ici"
  only:
    - master  # Déploy
