# Job de compilation
compile:
  stage: build
  script:
    - mkdir -p build
    - javac -d build src/main/java/control/GameController.java

# Job de test
test:
  stage: test
  script:
    - echo "Pas de tests définis pour le moment"

# Job de déploiement
deploy:
  stage: deploy
  script:
    - echo "Déploiement du code ici"
