# Spécifiez l'image Docker à utiliser comme base pour les jobs
image: openjdk:latest

# Définition des étapes du pipeline
stages:
  - build
  - test
  - deploy

# Job de compilation
compile:
  stage: build
  script:
    - mkdir -p build
    - javac -d build src/main/java/control/GameController.java

# Job de test
test:
  stage: test
  script:
    - mkdir -p build
    - javac -d build -cp "lib/*" "src/test/.*/.*"
    - java -cp "lib/*:build" org.junit.platform.console.ConsoleLauncher --scan-classpath

# Job de déploiement
deploy:
  stage: deploy
  script:
    - echo "Déploiement du code ici"
  only:
    - master  # Déployer uniquement à partir de la branche master
