# Spécifiez l'image Docker à utiliser comme base pour les jobs
image: openjdk:latest

# Définition des étapes du pipeline
stages:
  - build
  - test
  - deploy

# Job de compilation
compile:
  stage: build
  script:
    - javac -cp "lib/*" -d build src/main/java/app/* src/main/java/control/* src/main/java/model/* src/main/java/tools/* src/main/java/view/game/*.java src/main/java/view/*.java src/test/java/*/*
# Job de test pour un seul fichier
test:
  stage: test
  script:
    - java -cp "lib/*:build" org.junit.platform.console.ConsoleLauncher --scan-class-path
# Job de déploiement
deploy:
  stage: deploy
  script:
    - echo "Déploiement du code ici"
