# Spécifiez l'image Docker à utiliser comme base pour les jobs
image: openjdk:latest

# Définition des étapes du pipeline
stages:
  - build
  - test
  - deploy

# Job de compilation
compile:
  stage: build
  script:
    - mkdir -p build
    - javac -d build src/main/java/control/GameController.java
# Job de test pour un seul fichier
test:
  stage: test
  script:
    - mkdir -p build
    - ls lib/  # Affiche le contenu du répertoire "lib/" pour vérifier la présence de JUnit
    - javac -d build -cp "lib/*" src/test/java/control/GameControllerTest.java
    - ls build/  # Affiche le contenu du répertoire "build/" pour vérifier les fichiers générés
    - java -cp "lib/*:build" org.junit.platform.console.ConsoleLauncher --scan-classpath




# Job de déploiement
deploy:
  stage: deploy
  script:
    - echo "Déploiement du code ici"
